name: Update README with Current Date and Time

on:
  schedule:
    - cron: "0 * * * *"  # Se ejecuta cada hora en el minuto 0
  workflow_dispatch:    # Permite ejecutar el workflow manualmente

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config --global user.name "FullFran"
        git config --global user.email "franfi17sw@gmail.com"

    - name: Update README with current date and time
      run: |
        current_date=$(date +"%Y-%m-%d %H:%M %Z")
        # Usa sed para reemplazar el contenido entre los marcadores
        sed -i '/<!-- START_DATE -->/,/<!-- END_DATE -->/c<!-- START_DATE -->\n`'"$current_date"'`\n<!-- END_DATE -->' README.md

    - name: Commit changes
      run: |
        git add README.md
        # Solo realiza commit si hay cambios
        if ! git diff --cached --quiet; then
          git commit -m "🕒 Updated README with current date and time"
        else
          echo "No changes to commit"
        fi

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
