name: Update README with current date and time

on:
  schedule:
    - cron: "0 * * * *"  # Esto se ejecuta cada hora
  workflow_dispatch:  # Permite ejecutar manualmente el workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Update README with date
      run: |
        echo "Updating the README with the current date and time"
        current_date=$(date +"%Y-%m-%d %H:%M %Z")
        echo "### Hi there 👋" > README.md
        echo "" >> README.md
        echo "I'm currently studying for a Master's degree in Physics." >> README.md
        echo "I'm interested in artificial intelligence, automatizations and the simulation of physical models." >> README.md
        echo "I'm looking to improve my programming skills." >> README.md
        echo "" >> README.md
        echo "### 🕒 Current Date and Time:" >> README.md
        echo "\`\`\`" >> README.md
        echo "$current_date" >> README.md
        echo "\`\`\`" >> README.md

    - name: Commit changes
      run: |
        git config --global user.name "FullFran"
        git config --global user.email "franfi17sw@gmail.com"
        git add README.md
        git commit -m "Updated README with current date and time"
        git push
